name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Dockerfile
      run: docker build .
      working-directory: myapp

    - name: Build with docker-compose
      run: docker-compose up -d
      working-directory: myapp

    - name: Test
      run: go test ./...
      working-directory: myapp

    - name: Build
      run: go build ./...
      working-directory: myapp